name: Check Base Branch

on:
  pull_request:
    branches:
      - '*'

jobs:
  check-base-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is to main-dev-branch
        run: |
          if [ "${{ github.base_ref }}" != "main-dev-branch" ]; then
            echo "Pull Request must be made to 'main-dev-branch'."
            exit 1
          fi
        shell: bash
